name: assinantes
recipe: wordpress
config:
  php: '8.1'
  via: apache
  composer_version: '2'
  webroot: .
  database: mysql

services:
  appserver:
    type: php:8.1
    via: apache
    webroot: .
    ssl: true  # Habilita SSL para o appserver
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database

proxy:
  appserver:
    - assinantes.lndo.site
    - assinantes.lndo.site:443
  mailhog:
    - mail.assinantes.lndo.site
    - mail.assinantes.lndo.site:443
  pma:
    - pma.assinantes.lndo.site
    - pma.assinantes.lndo.site:443
