name: assine
recipe: wordpress
config:
  php: '8.1'
  via: apache
  composer_version: '2'
  webroot: .
  database: mysql

services:
  appserver:
    type: php:8.1
    via: apache
    webroot: .
    ssl: true  
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database

proxy:
  appserver:
    - assine.lndo.site
  mailhog:
    - mail.assine.lndo.site
  pma:
    - pma.assine.lndo.site
