version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: srv-captain--assine-developer-db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: 7221c945d8e65542
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 7221c945d8e65542
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: 7221c945d8e65542

volumes:
  db_data:
